# Generated by Django 5.2.12 on 2026-04-16 00:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание условия получения')),
                ('icon', models.CharField(default='🏆', max_length=50, verbose_name='Иконка/эмодзи')),
                ('badge_color', models.CharField(default='#FFD700', max_length=7, verbose_name='Цвет бейджа (hex)')),
                ('ach_type', models.CharField(choices=[('streak', 'Серия дней'), ('score', 'Результат'), ('completion', 'Завершение'), ('speed', 'Скорость'), ('accuracy', 'Точность'), ('social', 'Социальное')], max_length=15, verbose_name='Тип ачивки')),
                ('condition_value', models.PositiveIntegerField(default=1, verbose_name='Пороговое значение условия')),
                ('xp_reward', models.PositiveIntegerField(default=50, verbose_name='Бонус XP')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Скрытая')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название раздела')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка (CSS-класс)')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Логин')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('role', models.CharField(choices=[('student', 'Ученик'), ('teacher', 'Учитель'), ('admin', 'Администратор')], default='student', max_length=10, verbose_name='Роль')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('total_xp', models.PositiveIntegerField(default=0, verbose_name='Опыт (XP)')),
                ('game_level', models.PositiveSmallIntegerField(default=1, verbose_name='Уровень')),
                ('streak_days', models.PositiveIntegerField(default=0, verbose_name='Дней подряд')),
                ('last_activity', models.DateField(blank=True, null=True, verbose_name='Последняя активность')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название класса')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_classes', to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='class_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='quiz_app.classgroup', verbose_name='Класс'),
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('weekly', 'Недельный'), ('monthly', 'Месячный'), ('all', 'За всё время')], default='weekly', max_length=10, verbose_name='Период')),
                ('rank', models.PositiveSmallIntegerField(verbose_name='Место')),
                ('total_xp', models.PositiveIntegerField(verbose_name='XP за период')),
                ('tasks_done', models.PositiveIntegerField(default=0, verbose_name='Заданий выполнено')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('week_start', models.DateField(blank=True, null=True, verbose_name='Начало недели')),
                ('class_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboards', to='quiz_app.classgroup', verbose_name='Класс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись таблицы лидеров',
                'verbose_name_plural': 'Таблица лидеров',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('INFO', 'Информация'), ('WARNING', 'Предупреждение'), ('ERROR', 'Ошибка')], default='INFO', max_length=10)),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Системный лог',
                'verbose_name_plural': 'Системные логи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название задания')),
                ('description', models.TextField(blank=True, verbose_name='Описание / условие')),
                ('task_type', models.CharField(choices=[('math_path', 'Математический путь'), ('single', 'Тест (один ответ)'), ('multi', 'Тест (несколько ответов)'), ('text_input', 'Развёрнутый ответ'), ('matching', 'Соответствие')], default='math_path', max_length=15, verbose_name='Тип задания')),
                ('difficulty', models.IntegerField(choices=[(1, 'Лёгкий'), (2, 'Средний'), (3, 'Сложный')], default=2, verbose_name='Сложность')),
                ('xp_reward', models.PositiveIntegerField(default=10, verbose_name='Награда XP')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_value', models.IntegerField(blank=True, null=True, verbose_name='Начальное значение')),
                ('target_value', models.IntegerField(blank=True, null=True, verbose_name='Целевое значение')),
                ('operation_1', models.CharField(blank=True, max_length=20, verbose_name='Операция 1 (напр. "+5" или "*2")')),
                ('operation_2', models.CharField(blank=True, max_length=20, verbose_name='Операция 2 (напр. "-3" или "/2")')),
                ('max_steps', models.PositiveSmallIntegerField(default=10, verbose_name='Максимум шагов')),
                ('optimal_steps', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Оптимальное кол-во шагов')),
                ('correct_answer_text', models.CharField(blank=True, max_length=500, verbose_name='Правильный ответ (текст)')),
                ('created_by', models.ForeignKey(limit_choices_to={'role__in': ['teacher', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['topic', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LevelAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_success', models.BooleanField(default=False, verbose_name='Успешно')),
                ('errors_made', models.PositiveSmallIntegerField(default=0, verbose_name='Ошибок сделано')),
                ('steps_taken', models.PositiveSmallIntegerField(default=0, verbose_name='Шагов сделано')),
                ('xp_earned', models.PositiveIntegerField(default=0, verbose_name='XP получено')),
                ('time_spent', models.PositiveIntegerField(default=0, verbose_name='Время (сек)')),
                ('solution_path', models.JSONField(blank=True, null=True, verbose_name='Путь решения')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz_app.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Попытка прохождения',
                'verbose_name_plural': 'Попытки прохождений',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст варианта')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный')),
                ('match_key', models.CharField(blank=True, max_length=200, verbose_name='Ключ соответствия')),
                ('match_value', models.CharField(blank=True, max_length=200, verbose_name='Значение соответствия')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quiz_app.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название темы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('theory_text', models.TextField(blank=True, verbose_name='Теоретический материал')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role__in': ['teacher', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='quiz_app.subject', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['subject', 'order'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='quiz_app.topic', verbose_name='Тема'),
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='Получено')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='quiz_app.achievement', verbose_name='Достижение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Достижение пользователя',
                'verbose_name_plural': 'Достижения пользователей',
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks_completed', models.PositiveIntegerField(default=0, verbose_name='Заданий пройдено')),
                ('tasks_total', models.PositiveIntegerField(default=0, verbose_name='Всего заданий')),
                ('total_errors', models.PositiveIntegerField(default=0, verbose_name='Ошибок всего')),
                ('best_score', models.PositiveIntegerField(default=0, verbose_name='Лучший результат')),
                ('total_xp_earned', models.PositiveIntegerField(default=0, verbose_name='XP за тему')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Тема завершена')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='quiz_app.topic', verbose_name='Тема')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прогресс пользователя',
                'verbose_name_plural': 'Прогресс пользователей',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
